/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's github repository
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_FUND_WATCH: () => VIEW_TYPE_FUND_WATCH,
  default: () => FundWatchPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_FUND_WATCH = "fund-watch-view";
var DEFAULT_SETTINGS = {
  funds: ["022458 fund", "588080 etf", "510310 etf", "513300 etf", "159696 etf"].join(
    "\n"
  ),
  refreshMinutes: 1
};
function parseFunds(raw) {
  const out = [];
  for (const line of raw.split(/\r?\n/)) {
    const parts = line.trim().split(/\s+/);
    if (parts.length === 0 || !parts[0]) continue;
    const code = parts[0];
    const explicit = parts[1];
    const type = explicit === "fund" || explicit === "etf" ? explicit : code.startsWith("5") || code.startsWith("1") ? "etf" : "fund";
    out.push({ code, type });
  }
  return out;
}
function secid(code) {
  const first = code[0];
  const sh = first === "6" || first === "9" || first === "5";
  return `${sh ? "1" : "0"}.${code}`;
}
async function fetchEtf(code) {
  const id = secid(code);
  const quoteUrl = `https://push2.eastmoney.com/api/qt/stock/get?secid=${id}&fields=f12,f14,f2,f3,f4`;
  const klineUrl = `https://push2his.eastmoney.com/api/qt/stock/kline/get?secid=${id}&fields1=f1,f2,f3&fields2=f51,f52&klt=101&fqt=1&end=20500101&lmt=30`;
  const [q, k] = await Promise.all([
    (0, import_obsidian.requestUrl)({ url: quoteUrl }).then((r) => r.json()),
    (0, import_obsidian.requestUrl)({ url: klineUrl }).then((r) => r.json())
  ]);
  const d = q?.data ?? {};
  const price = parseFloat(d.f2);
  const changePercent = parseFloat(d.f3);
  const klines = k?.data?.klines ?? [];
  const series = klines.map((s) => parseFloat(s.split(",")[1])).filter((n) => !isNaN(n));
  return {
    code,
    type: "etf",
    name: d.f14 ?? code,
    price: isNaN(price) ? 0 : price,
    changePercent: isNaN(changePercent) ? 0 : changePercent,
    series,
    updatedAt: (/* @__PURE__ */ new Date()).toLocaleTimeString("zh-CN", {
      hour: "2-digit",
      minute: "2-digit"
    })
  };
}
async function fetchFund(code) {
  const url = `https://fundmobapi.eastmoney.com/f10/fund/DWJZ?fundCode=${code}&pageIndex=1&pageSize=30`;
  const res = await (0, import_obsidian.requestUrl)({
    url,
    headers: { Referer: "https://m.fund.eastmoney.com/" }
  }).then((r) => r.json());
  const datas = res?.Datas ?? [];
  if (datas.length === 0) {
    return {
      code,
      type: "fund",
      name: code,
      price: 0,
      changePercent: 0,
      series: [],
      updatedAt: ""
    };
  }
  const navs = datas.map((d) => parseFloat(d.DWJZ)).filter((n) => !isNaN(n));
  const series = [...navs].reverse();
  const latest = navs[0];
  const prev = navs[1] ?? latest;
  const changePercent = prev ? (latest - prev) / prev * 100 : 0;
  return {
    code,
    type: "fund",
    name: res?.Expansion?.[0]?.FUND_NAME ?? code,
    price: latest,
    changePercent,
    series,
    updatedAt: datas[0]?.FSRQ ?? ""
  };
}
async function fetchSnapshot(cfg) {
  try {
    return cfg.type === "etf" ? await fetchEtf(cfg.code) : await fetchFund(cfg.code);
  } catch (e) {
    return {
      code: cfg.code,
      type: cfg.type,
      name: cfg.code,
      price: 0,
      changePercent: 0,
      series: [],
      updatedAt: "\u83B7\u53D6\u5931\u8D25"
    };
  }
}
function sparkline(series, color) {
  const w = 90;
  const h = 30;
  const pad = 3;
  if (series.length < 2) {
    return `<svg width="${w}" height="${h}"></svg>`;
  }
  const min = Math.min(...series);
  const max = Math.max(...series);
  const span = max - min || 1;
  const n = series.length;
  const pts = series.map((v, i) => {
    const x = pad + i / (n - 1) * (w - pad * 2);
    const y = h - pad - (v - min) / span * (h - pad * 2);
    return `${x.toFixed(1)},${y.toFixed(1)}`;
  }).join(" ");
  return `<svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><polyline points="${pts}" fill="none" stroke="${color}" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
}
function pctColor(p) {
  return p > 0 ? "#A32D2D" : p < 0 ? "#3B6D11" : "#888780";
}
var FundWatchView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.timer = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_FUND_WATCH;
  }
  getDisplayText() {
    return "\u57FA\u91D1\u52A8\u6001";
  }
  getIcon() {
    return "line-chart";
  }
  async onOpen() {
    this.render();
    this.startTimer();
  }
  async onClose() {
    this.stopTimer();
    this.contentEl.empty();
  }
  startTimer() {
    this.stopTimer();
    const ms = Math.max(1, this.plugin.settings.refreshMinutes) * 60 * 1e3;
    this.timer = window.setInterval(() => this.render(), ms);
  }
  stopTimer() {
    if (this.timer != null) {
      window.clearInterval(this.timer);
      this.timer = null;
    }
  }
  async render() {
    const root = this.contentEl;
    root.empty();
    root.addClass("fund-watch-root");
    const header = root.createDiv({ cls: "fw-header" });
    header.createDiv({ cls: "fw-title", text: "\u57FA\u91D1\u52A8\u6001" });
    const meta = header.createDiv({ cls: "fw-meta", text: "\u66F4\u65B0\u4E2D\u2026" });
    const btn = header.createEl("button", { cls: "fw-refresh", text: "\u21BB" });
    btn.addEventListener("click", () => {
      btn.classList.add("fw-spin");
      this.render().finally(
        () => window.setTimeout(() => btn.classList.remove("fw-spin"), 500)
      );
    });
    const funds = parseFunds(this.plugin.settings.funds);
    const snapshots = await Promise.all(funds.map(fetchSnapshot));
    meta.textContent = `\u5171 ${snapshots.length} \u53EA \xB7 ${(/* @__PURE__ */ new Date()).toLocaleTimeString(
      "zh-CN",
      { hour: "2-digit", minute: "2-digit" }
    )}`;
    const list = root.createDiv({ cls: "fw-list" });
    for (const s of snapshots) {
      const card = list.createDiv({ cls: "fw-card" });
      const info = card.createDiv({ cls: "fw-info" });
      info.createDiv({ cls: "fw-name", text: s.name || s.code });
      const sub = s.type === "fund" && s.updatedAt ? `${s.code} \xB7 \u51C0\u503C ${s.updatedAt}` : s.code;
      info.createDiv({ cls: "fw-code", text: sub });
      const chart = card.createDiv({ cls: "fw-chart" });
      chart.innerHTML = sparkline(s.series, pctColor(s.changePercent));
      const right = card.createDiv({ cls: "fw-right" });
      const pct = right.createDiv({ cls: "fw-pct" });
      pct.textContent = (s.changePercent > 0 ? "+" : "") + s.changePercent.toFixed(2) + "%";
      pct.style.color = pctColor(s.changePercent);
      right.createDiv({
        cls: "fw-price",
        text: s.price ? s.price.toFixed(4) : "\u2014"
      });
    }
  }
};
var FundWatchSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u57FA\u91D1\u52A8\u6001 \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u57FA\u91D1\u5217\u8868").setDesc(
      "\u6BCF\u884C\u4E00\u53EA\uFF0C\u683C\u5F0F\uFF1A\u4EE3\u7801 [etf|fund]\u3002etf \u4E3A\u573A\u5185\u5B9E\u65F6\u884C\u60C5\uFF0Cfund \u4E3A\u573A\u5916\u51C0\u503C\uFF08\u6BCF\u65E5\u66F4\u65B0\uFF09\u3002\u4E0D\u5199\u7C7B\u578B\u4F1A\u6309\u4EE3\u7801\u524D\u7F00\u81EA\u52A8\u5224\u65AD\u3002"
    ).addTextArea((t) => {
      t.inputEl.setAttr("rows", 8);
      t.inputEl.style.width = "100%";
      t.setValue(this.plugin.settings.funds).onChange(async (v) => {
        this.plugin.settings.funds = v;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u5237\u65B0\u95F4\u9694\uFF08\u5206\u949F\uFF09").setDesc("\u573A\u5185 ETF \u884C\u60C5\u8F6E\u8BE2\u95F4\u9694\uFF0C\u5EFA\u8BAE 1-5 \u5206\u949F\u3002").addText(
      (t) => t.setValue(String(this.plugin.settings.refreshMinutes)).onChange(async (v) => {
        this.plugin.settings.refreshMinutes = Math.max(
          1,
          parseInt(v) || 1
        );
        await this.plugin.saveSettings();
      })
    );
  }
};
var FundWatchPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_FUND_WATCH,
      (leaf) => new FundWatchView(leaf, this)
    );
    this.addRibbonIcon("line-chart", "\u6253\u5F00\u57FA\u91D1\u52A8\u6001", () => this.activateView());
    this.addCommand({
      id: "open-fund-watch",
      name: "\u6253\u5F00\u57FA\u91D1\u52A8\u6001\u9762\u677F",
      callback: () => this.activateView()
    });
    this.addSettingTab(new FundWatchSettingTab(this.app, this));
    new import_obsidian.Notice("\u57FA\u91D1\u52A8\u6001\uFF1A\u70B9\u51FB\u5DE6\u4FA7\u56FE\u8868\u56FE\u6807\u6253\u5F00\u9762\u677F");
  }
  async onunload() {
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_FUND_WATCH)[0] ?? null;
    if (!leaf) {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_FUND_WATCH, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
