/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's github repository
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_FUND_WATCH: () => VIEW_TYPE_FUND_WATCH,
  default: () => FundWatchPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_FUND_WATCH = "fund-watch-view";
var DEFAULT_SETTINGS = {
  funds: ["022458 fund", "588080 etf", "510310 etf", "513300 etf", "159696 etf"].join(
    "\n"
  ),
  refreshMinutes: 1
};
function parseFunds(raw) {
  const out = [];
  for (const line of raw.split(/\r?\n/)) {
    const parts = line.trim().split(/\s+/);
    if (parts.length === 0 || !parts[0]) continue;
    const code = parts[0];
    const explicit = parts[1];
    let type;
    if (explicit === "fund" || explicit === "etf") {
      type = explicit;
    } else if (code.startsWith("5") || code.startsWith("1")) {
      type = "etf";
    } else {
      type = "fund";
    }
    out.push({ code, type });
  }
  return out;
}
function secid(code) {
  const first = code[0];
  const sh = first === "6" || first === "9" || first === "5";
  return `${sh ? "1" : "0"}.${code}`;
}
function asJson(value) {
  return value;
}
async function fetchEtf(code) {
  const id = secid(code);
  const quoteUrl = `https://push2.eastmoney.com/api/qt/stock/get?secid=${id}&fields=f12,f14,f2,f3,f4`;
  const klineUrl = `https://push2his.eastmoney.com/api/qt/stock/kline/get?secid=${id}&fields1=f1,f2,f3&fields2=f51,f52&klt=101&fqt=1&end=20500101&lmt=30`;
  const qResp = await (0, import_obsidian.requestUrl)({ url: quoteUrl });
  const kResp = await (0, import_obsidian.requestUrl)({ url: klineUrl });
  const q = asJson(qResp.json());
  const k = asJson(kResp.json());
  const d = q.data ?? {};
  const price = parseFloat(d.f2 ?? "");
  const changePercent = parseFloat(d.f3 ?? "");
  const klines = k.data?.klines ?? [];
  const series = klines.map((s) => parseFloat(s.split(",")[1])).filter((n) => !isNaN(n));
  return {
    code,
    type: "etf",
    name: d.f14 ?? code,
    price: isNaN(price) ? 0 : price,
    changePercent: isNaN(changePercent) ? 0 : changePercent,
    series,
    updatedAt: (/* @__PURE__ */ new Date()).toLocaleTimeString("zh-CN", {
      hour: "2-digit",
      minute: "2-digit"
    })
  };
}
async function fetchFund(code) {
  const url = `https://fundmobapi.eastmoney.com/f10/fund/DWJZ?fundCode=${code}&pageIndex=1&pageSize=30`;
  const res = await (0, import_obsidian.requestUrl)({
    url,
    headers: { Referer: "https://m.fund.eastmoney.com/" }
  });
  const data = asJson(res.json());
  const datas = data.Datas ?? [];
  if (datas.length === 0) {
    return {
      code,
      type: "fund",
      name: code,
      price: 0,
      changePercent: 0,
      series: [],
      updatedAt: ""
    };
  }
  const navs = datas.map((d) => parseFloat(d.DWJZ)).filter((n) => !isNaN(n));
  const series = [...navs].reverse();
  const latest = navs[0];
  const prev = navs[1] ?? latest;
  const changePercent = prev ? (latest - prev) / prev * 100 : 0;
  return {
    code,
    type: "fund",
    name: data.Expansion?.[0]?.FUND_NAME ?? code,
    price: latest,
    changePercent,
    series,
    updatedAt: datas[0]?.FSRQ ?? ""
  };
}
function withTimeout(p, ms) {
  return new Promise((resolve, reject) => {
    const timer = window.setTimeout(() => reject(new Error("\u8BF7\u6C42\u8D85\u65F6")), ms);
    p.then(
      (v) => {
        window.clearTimeout(timer);
        resolve(v);
      },
      (e) => {
        window.clearTimeout(timer);
        reject(e);
      }
    );
  });
}
async function fetchSnapshot(cfg) {
  try {
    return cfg.type === "etf" ? await withTimeout(fetchEtf(cfg.code), 15e3) : await withTimeout(fetchFund(cfg.code), 15e3);
  } catch {
    return {
      code: cfg.code,
      type: cfg.type,
      name: cfg.code,
      price: 0,
      changePercent: 0,
      series: [],
      updatedAt: "\u83B7\u53D6\u5931\u8D25"
    };
  }
}
function sparkline(series, color) {
  const NS = "http://www.w3.org/2000/svg";
  const w = 90;
  const h = 30;
  const pad = 3;
  const svg = document.createElementNS(NS, "svg");
  svg.setAttribute("width", String(w));
  svg.setAttribute("height", String(h));
  svg.setAttribute("viewBox", `0 0 ${w} ${h}`);
  if (series.length >= 2) {
    const min = Math.min(...series);
    const max = Math.max(...series);
    const span = max - min || 1;
    const n = series.length;
    const pts = series.map((v, i) => {
      const x = pad + i / (n - 1) * (w - pad * 2);
      const y = h - pad - (v - min) / span * (h - pad * 2);
      return `${x.toFixed(1)},${y.toFixed(1)}`;
    }).join(" ");
    const pl = document.createElementNS(NS, "polyline");
    pl.setAttribute("points", pts);
    pl.setAttribute("fill", "none");
    pl.setAttribute("stroke", color);
    pl.setAttribute("stroke-width", "1.5");
    pl.setAttribute("stroke-linecap", "round");
    pl.setAttribute("stroke-linejoin", "round");
    svg.appendChild(pl);
  }
  return svg;
}
function pctColor(p) {
  return p > 0 ? "#A32D2D" : p < 0 ? "#3B6D11" : "#888780";
}
function pctClass(p) {
  return p > 0 ? "fw-up" : p < 0 ? "fw-down" : "fw-flat";
}
function nowHM() {
  return (/* @__PURE__ */ new Date()).toLocaleTimeString("zh-CN", {
    hour: "2-digit",
    minute: "2-digit"
  });
}
var FundWatchView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.timer = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_FUND_WATCH;
  }
  getDisplayText() {
    return "\u57FA\u91D1\u52A8\u6001";
  }
  getIcon() {
    return "line-chart";
  }
  async onOpen() {
    await this.render();
    this.startTimer();
  }
  async onClose() {
    this.stopTimer();
    this.contentEl.empty();
  }
  startTimer() {
    this.stopTimer();
    const ms = Math.max(1, this.plugin.settings.refreshMinutes) * 60 * 1e3;
    this.timer = window.setInterval(() => {
      void this.render();
    }, ms);
  }
  stopTimer() {
    if (this.timer != null) {
      window.clearInterval(this.timer);
      this.timer = null;
    }
  }
  async render() {
    const root = this.contentEl;
    root.empty();
    root.addClass("fund-watch-root");
    const header = root.createDiv({ cls: "fw-header" });
    header.createDiv({ cls: "fw-title", text: "\u57FA\u91D1\u52A8\u6001" });
    const meta = header.createDiv({ cls: "fw-meta", text: "\u66F4\u65B0\u4E2D\u2026" });
    const btn = header.createEl("button", { cls: "fw-refresh", text: "\u21BB" });
    btn.addEventListener("click", () => {
      btn.classList.add("fw-spin");
      void this.render().finally(
        () => window.setTimeout(() => btn.classList.remove("fw-spin"), 500)
      );
    });
    const list = root.createDiv({ cls: "fw-list" });
    const loading = list.createDiv({ cls: "fw-meta", text: "\u52A0\u8F7D\u4E2D\u2026" });
    try {
      const funds = parseFunds(this.plugin.settings.funds);
      const snapshots = await Promise.all(funds.map(fetchSnapshot));
      if (!list.isConnected) return;
      list.empty();
      meta.textContent = `\u5171 ${snapshots.length} \u53EA \xB7 ${nowHM()}`;
      for (const s of snapshots) {
        const card = list.createDiv({ cls: "fw-card" });
        const info = card.createDiv({ cls: "fw-info" });
        info.createDiv({ cls: "fw-name", text: s.name || s.code });
        const sub = s.type === "fund" && s.updatedAt ? `${s.code} \xB7 \u51C0\u503C ${s.updatedAt}` : s.updatedAt === "\u83B7\u53D6\u5931\u8D25" ? `${s.code} \xB7 \u83B7\u53D6\u5931\u8D25` : s.code;
        info.createDiv({ cls: "fw-code", text: sub });
        const chart = card.createDiv({ cls: "fw-chart" });
        chart.appendChild(sparkline(s.series, pctColor(s.changePercent)));
        const right = card.createDiv({ cls: "fw-right" });
        const pct = right.createDiv({
          cls: "fw-pct " + pctClass(s.changePercent)
        });
        pct.textContent = (s.changePercent > 0 ? "+" : "") + s.changePercent.toFixed(2) + "%";
        right.createDiv({
          cls: "fw-price",
          text: s.price ? s.price.toFixed(4) : "\u2014"
        });
      }
    } catch (err) {
      if (!list.isConnected) return;
      list.empty();
      list.createDiv({
        cls: "fw-meta",
        text: `\u52A0\u8F7D\u5931\u8D25\uFF1A${err instanceof Error ? err.message : String(err)}\uFF0C\u8BF7\u70B9\u51FB \u21BB \u91CD\u8BD5`
      });
      meta.textContent = "\u52A0\u8F7D\u5931\u8D25";
    }
  }
};
var DECLARATIVE_SETTINGS_VERSION = "1.13.0";
function supportsDeclarativeSettings() {
  const parse = (v) => v.split(".").map((s) => parseInt(s, 10) || 0);
  const cur = parse(import_obsidian.apiVersion);
  const min = parse(DECLARATIVE_SETTINGS_VERSION);
  for (let i = 0; i < 3; i++) {
    if ((cur[i] ?? 0) > (min[i] ?? 0)) return true;
    if ((cur[i] ?? 0) < (min[i] ?? 0)) return false;
  }
  return true;
}
var FundWatchSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
  }
  // 1.13.0+ 的声明式设置定义：让设置项进入全局设置搜索，并用于渲染。
  // 旧版本不识别此方法，会回落到下面的 display()。
  getSettingDefinitions() {
    if (!supportsDeclarativeSettings()) return [];
    return [
      {
        name: "\u57FA\u91D1\u5217\u8868",
        desc: "\u6BCF\u884C\u4E00\u53EA\uFF0C\u683C\u5F0F\uFF1A\u4EE3\u7801 [etf|fund]\u3002etf \u4E3A\u573A\u5185\u5B9E\u65F6\u884C\u60C5\uFF0Cfund \u4E3A\u573A\u5916\u51C0\u503C\uFF08\u6BCF\u65E5\u66F4\u65B0\uFF09\u3002\u4E0D\u5199\u7C7B\u578B\u4F1A\u6309\u4EE3\u7801\u524D\u7F00\u81EA\u52A8\u5224\u65AD\u3002",
        aliases: ["fund", "etf", "\u4EE3\u7801"],
        control: { type: "textarea", key: "funds", rows: 8 }
      },
      {
        name: "\u5237\u65B0\u95F4\u9694\uFF08\u5206\u949F\uFF09",
        desc: "\u573A\u5185 ETF \u884C\u60C5\u8F6E\u8BE2\u95F4\u9694\uFF0C\u5EFA\u8BAE 1-5 \u5206\u949F\u3002",
        control: { type: "number", key: "refreshMinutes", defaultValue: 1 }
      }
    ];
  }
  getControlValue(key) {
    if (key === "funds") return this.plugin.settings.funds;
    if (key === "refreshMinutes") return this.plugin.settings.refreshMinutes;
    return void 0;
  }
  setControlValue(key, value) {
    if (key === "funds" && typeof value === "string") {
      this.plugin.settings.funds = value;
      return this.plugin.saveSettings();
    }
    if (key === "refreshMinutes") {
      const n = Math.max(1, parseInt(String(value), 10) || 1);
      this.plugin.settings.refreshMinutes = n;
      return this.plugin.saveSettings();
    }
    return void 0;
  }
  // 兜底：旧版 Obsidian（< 1.13.0）走命令式渲染
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u57FA\u91D1\u52A8\u6001 \u8BBE\u7F6E").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u57FA\u91D1\u5217\u8868").setDesc(
      "\u6BCF\u884C\u4E00\u53EA\uFF0C\u683C\u5F0F\uFF1A\u4EE3\u7801 [etf|fund]\u3002etf \u4E3A\u573A\u5185\u5B9E\u65F6\u884C\u60C5\uFF0Cfund \u4E3A\u573A\u5916\u51C0\u503C\uFF08\u6BCF\u65E5\u66F4\u65B0\uFF09\u3002\u4E0D\u5199\u7C7B\u578B\u4F1A\u6309\u4EE3\u7801\u524D\u7F00\u81EA\u52A8\u5224\u65AD\u3002"
    ).addTextArea((t) => {
      t.inputEl.addClass("fw-textarea");
      t.inputEl.setAttr("rows", 8);
      t.setValue(this.plugin.settings.funds).onChange((v) => {
        this.plugin.settings.funds = v;
        return this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u5237\u65B0\u95F4\u9694\uFF08\u5206\u949F\uFF09").setDesc("\u573A\u5185 ETF \u884C\u60C5\u8F6E\u8BE2\u95F4\u9694\uFF0C\u5EFA\u8BAE 1-5 \u5206\u949F\u3002").addText(
      (t) => t.setValue(String(this.plugin.settings.refreshMinutes)).onChange((v) => {
        this.plugin.settings.refreshMinutes = Math.max(
          1,
          parseInt(v) || 1
        );
        return this.plugin.saveSettings();
      })
    );
  }
};
var FundWatchPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_FUND_WATCH, (leaf) => new FundWatchView(leaf, this));
    this.addRibbonIcon("line-chart", "\u6253\u5F00\u57FA\u91D1\u52A8\u6001", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-panel",
      name: "\u6253\u5F00\u57FA\u91D1\u52A8\u6001\u9762\u677F",
      callback: () => {
        void this.activateView();
      }
    });
    this.addSettingTab(new FundWatchSettingTab(this.app, this));
  }
  onunload() {
  }
  async activateView() {
    const { workspace } = this.app;
    try {
      const existing = workspace.getLeavesOfType(VIEW_TYPE_FUND_WATCH);
      if (existing.length > 0) {
        await existing[0].setViewState({
          type: VIEW_TYPE_FUND_WATCH,
          active: true
        });
        return;
      }
      let leaf = workspace.getRightLeaf(false);
      if (!leaf) leaf = workspace.getLeftLeaf(false);
      if (!leaf) leaf = workspace.getLeaf(true);
      if (!leaf) {
        new import_obsidian.Notice("\u57FA\u91D1\u52A8\u6001\uFF1A\u65E0\u6CD5\u521B\u5EFA\u89C6\u56FE\uFF0C\u8BF7\u91CD\u542F Obsidian \u540E\u91CD\u8BD5");
        return;
      }
      await leaf.setViewState({ type: VIEW_TYPE_FUND_WATCH, active: true });
    } catch (err) {
      console.error("[fund-watch] activateView failed:", err);
      new import_obsidian.Notice(
        `\u57FA\u91D1\u52A8\u6001\u6253\u5F00\u5931\u8D25\uFF1A${err instanceof Error ? err.message : String(err)}`
      );
    }
  }
  async loadSettings() {
    const data = asJson(
      await this.loadData()
    );
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data ?? {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
